#
# Your Crowdin credentials: ID and token are provided through GitHub Action secrets.
#
"project_id_env" : "CROWDIN_PROJECT_ID"
"api_token_env" : "CROWDIN_PERSONAL_TOKEN"
"base_path" : "."
"base_url" : "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": false

#
# Files configuration
#
files: [
    {
      #
      # Source files filter
      # e.g. "/resources/en/*.json"
      #
        "source" : "/common/src/commonMain/composeResources/values/*.xml",

      #
      # Where translations will be placed
      # e.g. "/resources/%two_letters_code%/%original_file_name%"
      #
        "translation" : "/common/src/commonMain/composeResources/values-%android_code%/%original_file_name%",

      #
      # File type
      # e.g. "json"
      #
        "type" : "android",

      #
      # The parameter "update_option" is optional. If it is not set, after the files update the translations for changed
      # strings will be removed. Use to fix typos and for minor changes in the source strings
      # e.g. "update_as_unapproved" or "update_without_changes"
      #
        "update_option" : "update_as_unapproved",

      #
      # Defines whether to translate tags attributes.
      # e.g. 0 or 1  (Default is 1)
      #
        "translate_attributes" : 0,

      #
      # Defines whether to split long texts into smaller text segments
      # e.g. 0 or 1 (Default is 1)
      #
        "content_segmentation" : 0,
    },
    {
      #
      # Source files filter
      # e.g. "/resources/en/*.json"
      #
        "source" : "/listing/google/base/*.html",

      #
      # Where translations will be placed
      # e.g. "/resources/%two_letters_code%/%original_file_name%"
      #
        "translation" : "/listing/google/%android_code%/%original_file_name%",

      #
      # File type
      # e.g. "json"
      #
        "type" : "html",

      #
      # The parameter "update_option" is optional. If it is not set, after the files update the translations for changed
      # strings will be removed. Use to fix typos and for minor changes in the source strings
      # e.g. "update_as_unapproved" or "update_without_changes"
      #
        "update_option" : "update_as_unapproved",

      #
      # Defines whether to translate tags attributes.
      # e.g. 0 or 1  (Default is 1)
      #
        "translate_attributes" : 0,

      #
      # Defines whether to split long texts into smaller text segments
      # e.g. 0 or 1 (Default is 1)
      #
        "content_segmentation" : 0,
    },
    {
      #
      # Source files filter
      # e.g. "/resources/en/*.json"
      #
        "source" : "/listing/google/base/*.xml",

      #
      # Where translations will be placed
      # e.g. "/resources/%two_letters_code%/%original_file_name%"
      #
        "translation" : "/listing/google/%android_code%/%original_file_name%",

      #
      # File type
      # e.g. "json"
      #
        "type" : "android",

      #
      # The parameter "update_option" is optional. If it is not set, after the files update the translations for changed
      # strings will be removed. Use to fix typos and for minor changes in the source strings
      # e.g. "update_as_unapproved" or "update_without_changes"
      #
        "update_option" : "update_as_unapproved",

      #
      # Defines whether to translate tags attributes.
      # e.g. 0 or 1  (Default is 1)
      #
        "translate_attributes" : 0,

      #
      # Defines whether to split long texts into smaller text segments
      # e.g. 0 or 1 (Default is 1)
      #
        "content_segmentation" : 0,
    }
]
