name: "✔️ Check Licenses"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**/*.gradle*'
      - 'gradle/**'
  pull_request:
    branches:
      - master
    paths:
      - '**/*.gradle*'
      - 'gradle/**'

jobs:
  check-licenses:
    name: Check Licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set up JDK 17"
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: "Check licenses"
        uses: eskatos/gradle-command-action@v3
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}
        with:
          arguments: licensee
