name: "⬆️ GitHub release -> Homebrew PR"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  new-update:
    name: Deploy Homebrew
    runs-on: macos-latest
    steps:
      - name: "Checkout main repo"
        uses: actions/checkout@v4
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Set up Git
        run: |
          git config --global user.email mail@artemchep.com
          git config --global user.name AChep
      - name: Update Homebrew cask
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.DEPLOY_HOMEBREW_GITHUB_TOKEN }}
        run: |
          brew tap AChep/cask
          brew update
          brew bump-cask-pr keyguard
