name: "🌐 Upload Google Play Store listing"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'listing/google/**'
      # Configuration.
      - '.github/update_google_play_listing.py'
      - '.github/update_google_play_listing.requirements.py'

jobs:
  sync-google-listing:
    name: Upload Google Play Store listing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r .github/update_google_play_listing.requirements.txt
      - name: "Setup secrets"
        run: |
          echo ${{ secrets.SERVICE_ACCOUNT_B64 }} | base64 -d | zcat >> service-account-google.json
      - name: "Update listing"
        run: |
          python .github/update_google_play_listing.py
